[package]
name = "kernel"
version = "0.1.0"
edition = "2021"
proc-macro = true

[dependencies]
limine = "0.2.0"
x86_64 = "0.15.1"
pic8259 = "0.11.0"
spin = "0.9.8"
pc-keyboard = "0.7.0"
linked_list_allocator = "0.10.5"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
